version: "3"
services:
    api:
      build:
        context: .
        dockerfile: src/Bancor.Api/Dockerfile
      ports:
        - "5555:80"  
      depends_on:
        - silo-host
        - consul 
      networks: 
        - "bancor-net"
      environment:
        - ASPNETCORE_ENVIRONMENT=Integration
    silo-host:
      build:
        context: .
        dockerfile: src/Bancor.SiloHost/Dockerfile
      depends_on:
        - db
        - consul
      networks: 
        - "bancor-net"
      environment:
        - ASPNETCORE_ENVIRONMENT=Integration
    db:
      image: "mongo"
      networks: 
        - "bancor-net"
      ports:
          - "27055:27055"        
    consul:
      image: consul:latest
      networks:
        - "bancor-net"
      command: consul agent -server -bootstrap -dev -client 0.0.0.0
networks:
  bancor-net:
