version: "3"
services:
    api:
      build:
        context: .
        dockerfile: src/Bancor.Api/Dockerfile
      ports:
        - "5001:80"
      depends_on:
        - silo-host
    silo-host:
      build:
        context: .
        dockerfile: src/Bancor.SiloHost/Dockerfile
      depends_on:
        - db        
    db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          SA_PASSWORD: "MyPassword001"
          ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"        