version: "3"
services:
    api:
      build:
        context: .
        dockerfile: src/Bancor.Api/Dockerfile
      ports:
        - "5555:80"  
      depends_on:
        - silo-host
        - consul 
      networks: 
        - "bancor-net"
      environment:
        - ASPNETCORE_ENVIRONMENT=Integration
    silo-host:
      build:
        context: .
        dockerfile: src/Bancor.SiloHost/Dockerfile
      depends_on:
        - db
        - consul
      networks: 
        - "bancor-net"
      environment:
        - ASPNETCORE_ENVIRONMENT=Integration
    db:
      image: "microsoft/mssql-server-linux:2017-latest"
      environment:
          SA_PASSWORD: "MyPassword001"
          ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"
      networks: 
        - "bancor-net"
    consul:
      image: consul:latest
      networks:
        - "bancor-net"
      command: consul agent -dev -client 0.0.0.0

networks:
  bancor-net:
