version: "3"
services:
    api:
      build:
        context: .
        dockerfile: src/Bancor.Api/Dockerfile
      depends_on:
        - silo-host
      networks: 
        - "bancor-net"
    silo-host:
      build:
        context: .
        dockerfile: src/Bancor.SiloHost/Dockerfile
      depends_on:
        - db        
      networks: 
        - "bancor-net"
    db:
      image: "microsoft/mssql-server-linux:2017-latest"
      environment:
          SA_PASSWORD: "MyPassword001"
          ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"
      networks: 
        - "bancor-net"
networks:
  bancor-net:
